### PR TITLE
Removing pressure limitations, to unify behavior to BME280

### PR DESCRIPTION
**Pull request by jposada202020**
Solves #29 . Unifying code with BME280 (adafruit/Adafruit_CircuitPython_BME280#45)

Thanks

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
How about we add a comment to the docstring, something like:

"The operational range of the BMP280 is 300-1100 hPa. Pressure measurements outside this range may not be as accurate."

I should have asked for that in the issue, sorry.

**Comment by jposada202020** [comment]
Perfect I like the idea, just to better explain things, I will verify the other library and added there also if needed, tonight :) Thanks!

**Comment by jposada202020** [comment]
@dhalbert I included the note as suggested in https://github.com/adafruit/Adafruit_CircuitPython_BMP280/pull/30/commits/dfc60112ba29760d83e6e466296bf76b69051d00 Thanks :)

**Review by dhalbert — APPROVED** [review]
:+1:

**Pull request merged**
